image: ubuntu/lts

packages:
  - autoconf
  - automake
  - bison
  - flex
  - python3-venv
  - imagemagick
  - graphviz
  - fig2dev
  - help2man
  - plotutils

sources:
  - https://git.sr.ht/~zondo/ifm

tasks:
  - config: |
      cd ifm
      sh autogen.sh
      ./configure
  - build: |
      cd ifm
      make -j2
  - test: |
      cd ifm/tests
      make check
  - htmldoc: |
      cd ifm/doc
      make html
  - dist: |
      cd ifm
      make distcheck

triggers:
  - condition: failure
    action: email
    to: zondo42@gmail.com
