## usage:
##   make ifmfile=mapfile.ifm TARGET
.PHONY: default all
default: map text raw
all: default pdfmap html

ifndef src
$(warning Usage: 'make ifm=FILE.ifm TARGET')
$(error 'ifm' not set)
endif

BASENAME = $(basename $(ifm))
SRCFILE = $(BASENAME).ifm
PAPERSIZE = a4

################################################################################
# PRIMARY TARGETS
PSMAPFILE = $(BASENAME).map.ps
PDFMAPFILE = $(BASENAME).map.pdf

TASKFILE = $(BASENAME).tasks.txt
ITEMFILE = $(BASENAME).items.txt

RAWMAPFILE = $(BASENAME).map.raw
RAWTASKFILE = $(BASENAME).tasks.raw
RAWITEMFILE = $(BASENAME).items.raw

HTMLINDEXFILE = $(BASENAME)-index.html

PSDOTFILE = $(BASENAME).dot.ps
PDFDOTFILE = $(BASENAME).dot.pdf

IFMOPTS =
# IFMOPTS = "-S verbose"

.PHONY: map tasks items text dot pdfmap pdfdot rawmap rawtasks rawitems raw

map: $(PSMAPFILE)
tasks: $(TASKFILE)
items: $(ITEMFILE)
text:  $(TASKFILE) $(ITEMFILE)

rawmap: $(RAWMAPFILE)
rawtasks: $(RAWTASKFILE)
rawitems: $(RAWITEMFILE)
raw: $(RAWITEMFILE) $(RAWTASKFILE) $(RAWMAPFILE)

html: $(HTMLINDEXFILE)

pdfmap: $(PDFMAPFILE)
dot: $(PSDOTFILE)
pdfdot: $(PDFDOTFILE)

%.tasks.txt: %.ifm
	@$(REPORT)
	ifm $(IFMOPTS) -t -f text -o $@ $<

%.items.txt: %.ifm
	@$(REPORT)
	ifm $(IFMOPTS) -i -f text -o $@ $<

%.map.raw: %.ifm
	@$(REPORT)
	ifm $(IFMOPTS) -m -f raw -o $@ $<
%.tasks.raw: %.ifm
	@$(REPORT)
	ifm $(IFMOPTS) -t -f raw -o $@ $<
%.items.raw: %.ifm
	@$(REPORT)
	ifm $(IFMOPTS) -i -f raw -o $@ $<

%-index.html: %.ifm
	@$(REPORT)
	ifm2html $<

%.map.ps: %.ifm
	@$(REPORT)
	ifm $(IFMOPTS) -m -f ps -o $@ $<

%.dot.dot: %.ifm
	@$(REPORT)
	ifm $(IFMOPTS) -t -f dot -o $@ $<

%.ps: %.dot
	@$(REPORT)
	dot -Tps -o $@ $<

%.pdf: %.ps
	@$(REPORT)
	ps2pdf -sPAPERSIZE=$(PAPERSIZE) $< $@


################################################################################
# CLEANUP
.PHONY: clean
clean:
	@rm -fv $(PDFMAPFILE) $(PSMAPFILE)
	@rm -fv $(TASKFILE) $(ITEMFILE)
	@rm -fv $(RAWTASKFILE) $(RAWITEMFILE) $(RAWMAPFILE)
	@rm -fv $(PSDOTFILE) $(PDFDOTFILE)

################################################################################
.PHONY: help
help:
	@echo
	@echo "TARGETS"
	@echo "   (pdf)map"
	@echo "   tasks"
	@echo "   items"
	@echo "   (pdf)dot"
	@echo "   clean"
	@echo

## a handy macro
REPORT=echo -e '\n\n======== Making $@ ========\n'

